insert into public.job_categories (name, english_name, slug, short_description, display_order, status) values
('Thiết bị & Ứng dụng', 'Technical & Application', 'technical', 'Thiết bị vận hành ổn định, kết quả được tin cậy.', 1, 'published'),
('LIS / IT / Data', 'LIS / IT / Data', 'lis', 'Dữ liệu đi đúng đường, phòng xét nghiệm chạy liền mạch.', 2, 'published'),
('Kinh doanh & Vận hành', 'Commercial & Operations', 'commercial', 'Đúng giải pháp, đúng nhu cầu, đúng cam kết.', 3, 'published'),
('Khối hỗ trợ', 'Corporate Functions', 'ops', 'Các vai trò hỗ trợ giúp đội ngũ vận hành hiệu quả.', 4, 'published')
on conflict (slug) do update set name = excluded.name, english_name = excluded.english_name, short_description = excluded.short_description, display_order = excluded.display_order, status = excluded.status;

insert into public.jobs (code, slug, title, category_id, location, employment_type, short_description, description, requirements, benefits, posted_at, status, display_order)
select v.code, v.slug, v.title, c.id, v.location, 'Toàn thời gian', v.summary, v.description::jsonb, v.requirements::jsonb, '[]'::jsonb, date '2026-09-04', 'published', v.display_order
from (values
('HN-SALES','hn-sales','[HN] Nhân viên Kinh doanh Thiết bị Y tế & Hóa chất tiêu hao (Sinh hóa – Miễn dịch)','Kinh doanh & Vận hành','Hà Nội','Tìm hiểu thị trường, phát triển khách hàng và tư vấn thiết bị, hóa chất xét nghiệm phù hợp.','["Tìm hiểu thị trường, đối thủ, sản phẩm và khách hàng.","Tìm kiếm khách hàng mới và phát triển quan hệ kinh doanh.","Tư vấn sản phẩm, thiết bị phù hợp và đàm phán với khách hàng."]','["Đại học khối xét nghiệm, y dược, điện tử y sinh hoặc công nghệ sinh học.","Tối thiểu 01 năm kinh nghiệm công nghệ y tế, dược phẩm hoặc sales ETC.","Giao tiếp, đàm phán, thuyết trình tốt."]',1),
('HN-DEV','hn-developer','[HN] Nhân viên Lập trình Phần mềm','LIS / IT / Data','Hà Nội','Phát triển ứng dụng web và Windows cho dự án nội bộ và khách hàng trong Digital Healthcare/MedTech.','["Phát triển ứng dụng web và Windows.","Gỡ lỗi, sửa đổi chương trình và kết nối cơ sở dữ liệu.","Báo cáo tiến độ và xử lý lỗi khi triển khai tại khách hàng."]','["Tốt nghiệp đại học, cao đẳng ngành liên quan.","Có kinh nghiệm với Web Services, JavaScript, ReactJS, HTML.","Hiểu C#, .NET Framework và SQL Server hoặc MySQL."]',2),
('HN-ACCOUNTANT','hn-accountant','[HN] Kế toán trưởng (Không quản lý nhân viên)','Khối hỗ trợ','Hà Nội','Kiểm soát tài chính, công nợ, chứng từ, báo cáo luật định và các vấn đề thuế của Công ty.','["Kiểm tra các khoản thu chi và nghĩa vụ ngân sách.","Rà soát, đối chiếu và thu hồi công nợ.","Chịu trách nhiệm hoạt động tài chính kế toán và báo cáo theo luật định."]','["Đại học chuyên ngành Tài chính, Kế toán doanh nghiệp.","Tối thiểu 03 năm kinh nghiệm Kế toán trưởng hoặc kiểm toán Big 4.","Am hiểu pháp luật thuế và chuẩn mực tài chính kế toán."]',3),
('HN-RD','hn-rd','[HN] Nhân viên R&D (Phát triển sản phẩm thương mại)','Kinh doanh & Vận hành','Hà Nội','Nghiên cứu xu hướng xét nghiệm, tìm kiếm sản phẩm mới và phát triển cơ hội kinh doanh trong ngành y tế.','["Tìm kiếm ý tưởng sản phẩm theo chiến lược Công ty.","Nghiên cứu thị trường và xu hướng sản phẩm xét nghiệm.","Xây dựng mạng lưới với các công ty Diagnostic và triển khai thử sản phẩm mới."]','["Đại học chuyên ngành y, dược, xét nghiệm hoặc công nghệ sinh học.","Ít nhất 2 năm kinh nghiệm phát triển thị trường hoặc sản phẩm.","Có kiến thức thị trường xét nghiệm và tiếng Anh lưu loát."]',4),
('HN-TECHNICIAN','hn-technician','[HN] Kỹ thuật viên Bảo trì Bảo dưỡng Thiết bị Y tế','Thiết bị & Ứng dụng','Hà Nội','Lắp đặt, bảo trì máy xét nghiệm, khảo sát hiện trường và phối hợp xử lý sự cố tại khách hàng.','["Lắp đặt máy xét nghiệm mới.","Bảo trì, bảo dưỡng máy xét nghiệm tại khách hàng.","Phối hợp hỗ trợ kỹ sư giải quyết sự cố và khảo sát hiện trường."]','["Cao đẳng/Đại học Điện tử, Điện tử y sinh, Điện tử viễn thông hoặc Tự động hóa.","Không yêu cầu kinh nghiệm, chấp nhận sinh viên mới ra trường.","Đọc hiểu tài liệu kỹ thuật tiếng Anh và sẵn sàng đi công tác."]',5),
('HN-AUTOMATION','hn-automation','[HN] Nhân viên Phụ trách Sản phẩm (Ngành hàng Automation)','Kinh doanh & Vận hành','Hà Nội','Quản lý danh mục Automation & AI, phát triển thị trường, hỗ trợ kinh doanh và triển khai giải pháp.','["Quản lý danh mục sản phẩm và giải pháp Automation, AI.","Phân tích thị trường, khách hàng và xu hướng công nghệ.","Tư vấn, xây dựng và trình bày giải pháp Automation và AI."]','["Đại học chuyên ngành y, dược, xét nghiệm, công nghệ sinh học, điện tử y sinh hoặc tự động hóa.","Ít nhất 03 năm kinh nghiệm phát triển sản phẩm hoặc tư vấn giải pháp.","Có kiến thức tự động hóa và phân tích dữ liệu tốt."]',6),
('HN-ENGINEER','hn-engineer','[HN] Kỹ sư Bảo trì Bảo dưỡng Thiết bị Y tế','Thiết bị & Ứng dụng','Hà Nội','Lắp đặt, bảo trì và bảo dưỡng thiết bị xét nghiệm tại khu vực được phân công, phối hợp hỗ trợ khách hàng.','["Lắp đặt máy xét nghiệm mới.","Bảo trì, bảo dưỡng máy xét nghiệm tại khách hàng.","Phối hợp hỗ trợ kỹ sư giải quyết sự cố và khảo sát hiện trường."]','["Cao đẳng/Đại học Điện tử, Điện tử y sinh, Điện tử viễn thông hoặc Tự động hóa.","Ứng viên có từ 1 năm kinh nghiệm trở lên.","Đọc hiểu tài liệu kỹ thuật tiếng Anh và sẵn sàng đi công tác."]',7)
) as v(code,slug,title,category,location,summary,description,requirements,display_order)
join public.job_categories c on c.name = v.category
on conflict (code) do update set title = excluded.title, category_id = excluded.category_id, location = excluded.location, short_description = excluded.short_description, description = excluded.description, requirements = excluded.requirements, display_order = excluded.display_order, status = excluded.status;

insert into public.faq_categories (name, slug, display_order, status) values
('Ứng tuyển','application',1,'published'),('CV','cv',2,'published'),('Phỏng vấn','interview',3,'published'),('Kết quả','result',4,'published'),('Offer','offer',5,'published'),('Quyền lợi','benefits',6,'published'),('Công tác','travel',7,'published'),('Dữ liệu ứng viên','candidate-data',8,'published'),('Thông tin tuyển dụng chính thức','official-recruitment',9,'published') on conflict (slug) do nothing;

insert into public.faqs (question, answer, category_id, display_order, published, status)
select v.question, v.answer, c.id, v.display_order, true, 'published' from (values
('Mình muốn ứng tuyển thì bắt đầu từ đâu?','Bạn hãy chọn vị trí phù hợp, đọc kỹ JD và gửi CV theo đúng hướng dẫn trên JD Mitalab. Career Hub này không nhận hồ sơ thay cho kênh chính thức.',1),
('Mình có thể ứng tuyển nhiều vị trí cùng lúc không?','Có. Bạn chỉ cần ghi rõ vị trí ưu tiên số 1 để đội ngũ Tuyển dụng hiểu định hướng của mình.',2),
('Mitalab có cơ hội cho intern hoặc sinh viên mới ra trường không?','Điều này tùy từng JD. Bạn có thể đăng ký Talent Community để nhận thông tin sớm khi có vị trí phù hợp.',3),
('Các vị trí hiện làm việc ở đâu?','Mitalab có văn phòng tại Hà Nội, TP.HCM, Đà Nẵng và Cần Thơ. Một số vai trò field service sẽ cần di chuyển.',4),
('Mình chưa học y khoa thì có ứng tuyển được không?','Bạn vẫn có thể ứng tuyển nếu phù hợp với yêu cầu JD. Mỗi nhóm nghề có nền tảng ưu tiên khác nhau.',5),
('Sau khi gửi hồ sơ, bao lâu mình sẽ nhận được phản hồi?','Mitalab xác nhận hồ sơ ngay khi tiếp nhận; sàng lọc trong khoảng ≤3 ngày làm việc và cập nhật kết quả theo từng bước.',6),
('Nếu chưa thấy vị trí phù hợp thì mình nên làm gì?','Bạn có thể đăng ký Talent Community để Mitalab có cơ sở kết nối khi xuất hiện cơ hội phù hợp.',7)
) as v(question,answer,display_order) join public.faq_categories c on c.slug = 'application' on conflict do nothing;

insert into public.recruitment_steps (number, title, short_description, full_description, display_order, status) values
('BẮT ĐẦU','Khám phá cơ hội phù hợp','Tìm một công việc phù hợp với điều bạn muốn phát triển.','Khám phá các vị trí đang tuyển tại Mitalab theo nhóm nghề, địa điểm và lĩnh vực chuyên môn.',0,'published'),
('01','Gửi hồ sơ','Cho chúng tôi biết bạn là ai và điều bạn đang tìm kiếm.','Chọn vị trí phù hợp và gửi CV cùng các thông tin cần thiết.',1,'published'),
('02','Trao đổi cùng HR','Một cuộc trò chuyện để hai bên hiểu nhau hơn.','HR sẽ trao đổi về kinh nghiệm, mong muốn nghề nghiệp và thông tin quan trọng về vị trí.',2,'published'),
('03','Gặp gỡ đội ngũ chuyên môn','Cùng nói sâu hơn về công việc bạn sẽ thực sự đảm nhận.','Trao đổi với quản lý trực tiếp và đội ngũ chuyên môn về kinh nghiệm, kiến thức và kỳ vọng.',3,'published'),
('04','Nhận kết quả','Bạn sẽ được cập nhật về kết quả và bước tiếp theo.','Đội ngũ Tuyển dụng tổng hợp đánh giá và phản hồi kết quả đến bạn.',4,'published'),
('05','Đề nghị nhận việc','Khi hai bên cùng nhìn thấy một sự phù hợp.','HR trao đổi rõ về vị trí, chính sách và thời điểm dự kiến bắt đầu công việc.',5,'published'),
('06','Chào mừng bạn gia nhập Mitalab','Hành trình ứng tuyển kết thúc. Một hành trình mới bắt đầu.','Mitalab gửi các thông tin cần thiết để chuẩn bị cho ngày làm việc đầu tiên.',6,'published') on conflict do nothing;

insert into public.career_stories (slug,title,eyebrow,category,job_family,short_description,cta_label,cta_url,published_date,featured,story_type,status) values
('miseq-i100-plus','Lắp đặt MiSeq i100 Plus đầu tiên tại Việt Nam','FIELD NOTES','Technical','Technical','Một lát cắt thực tế về công việc triển khai thiết bị, bàn giao công nghệ và hỗ trợ kỹ thuật cho đối tác.','Xem câu chuyện & nguồn ↗','https://www.mitalab.com/mitalab-lap-dat-cong-nghe-giai-trinh-tu-gen-moi-miseq-i100-plus-dau-tien-tai-viet-nam.html','2026-09-04',true,'mitalab_story','published'),
('kick-off-meeting-2026','Kick-off Meeting 2026: Đồng hành phát triển','GROWING TOGETHER','Culture','All','Ghi nhận thành tích, mục tiêu BSC, cam kết đội ngũ và tinh thần học hỏi liên tục trong một năm mới.','Xem câu chuyện & nguồn ↗','https://www.mitalab.com/#news','2026-09-04',false,'mitalab_story','published'),
('team-building-2023','Team Building 2023: Trekking Together as One','TOGETHER AS ONE','Culture','All','Hành trình qua các thử thách Tâm thế, Hợp tác, Kỷ luật và Đồng nhất để kể câu chuyện văn hóa bằng trải nghiệm.','Xem câu chuyện & nguồn ↗','https://www.mitalab.com/#news','2026-09-04',false,'mitalab_story','published') on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, status = excluded.status;

insert into public.work_environment (number,title,description,evidence,reference_article,display_order,status) values
('01','Phát triển chuyên môn qua công việc','Các JD hiện hành nêu cơ hội tham gia khóa đào tạo kiến thức chuyên môn và kỹ năng mềm.','Đào tạo chuyên môn và học từ công việc thực tế.','https://www.mitalab.com/#services',1,'published'),
('02','Phát huy năng lực trong từng vai trò','Các hoạt động và tin tức Mitalab là nguồn tham khảo để tìm hiểu cách đội ngũ cùng phát triển và phối hợp.','Mục tiêu BSC, hoạt động nội bộ và trao đổi chuyên môn.','https://www.mitalab.com/#news',2,'published'),
('03','Hợp tác và chia sẻ trong công việc','Team Building Together as One truyền tải văn hóa và tinh thần đội nhóm bằng trải nghiệm.','Tâm thế, Hợp tác, Kỷ luật và Đồng nhất.','https://www.mitalab.com/mitalab-team-building-2023-trekking-together-one.html',3,'published');
insert into public.company_values (name, display_order, status) values ('Uy tín',1,'published'),('Trách nhiệm',2,'published'),('Hợp tác',3,'published'),('Kỷ luật',4,'published'),('Sáng tạo',5,'published'),('Hiệu quả',6,'published') on conflict (name) do nothing;

insert into public.homepage_content (id,eyebrow,headline_line_1,headline_line_2,description,cta_1_label,cta_1_url,cta_2_label,cta_2_url,metrics,status) values (true,'CAREER HUB 2027 · BẢN MẪU TƯƠNG TÁC','Khám phá cơ hội nghề nghiệp','Phát triển cùng Mitalab','Khám phá những vai trò kết nối thiết bị, dữ liệu và con người để góp phần nâng tầm chất lượng xét nghiệm tại Việt Nam.','Tìm vị trí phù hợp','#jobs','Xem quy trình tuyển dụng','#journey','[{"value":"25+","label":"Năm kinh nghiệm trên thị trường"},{"value":"800+","label":"Bệnh viện đối tác"},{"value":"500+","label":"Sản phẩm cung cấp"},{"value":"4","label":"Văn phòng làm việc trên toàn quốc"}]','published') on conflict (id) do update set eyebrow=excluded.eyebrow, headline_line_1=excluded.headline_line_1, headline_line_2=excluded.headline_line_2, description=excluded.description, metrics=excluded.metrics, status=excluded.status;

insert into public.contacts (region,email,phone,extension,display_order,status) values ('Tuyển dụng miền Bắc','tuyendung@mitalab.com','(024) 3628 8882','710',1,'published'),('Tuyển dụng miền Nam','tuyendunghcm@mitalab.com','(028) 39 97 24 56','6533',2,'published') on conflict do nothing;
insert into public.site_settings (key,value,status) values ('recruitment_disclaimer','{"text":"Mitalab không thu phí ứng viên trong bất kỳ vòng tuyển dụng nào."}','published'),('social_links','{"mitalabworks":"https://facebook.com/MitalabWorks","mitalab_company":"https://facebook.com/MitalabCompany","linkedin":"https://www.mitalab.com/","website":"https://www.mitalab.com/"}','published') on conflict (key) do update set value=excluded.value, status=excluded.status;
